### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by patrickwerz** [Vinu-MysteriousTechVision/TestProjectRNNavigationV2#1]
Hi, I cannot rund the application with 

npm install
react-native run-android

I get the following message:

`Application Sample3RNNavigationV2 has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').

This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.

runApplication
    AppRegistry.js:180:6
__callFunction
    MessageQueue.js:353:47
<unknown>
    MessageQueue.js:118:26
__guardSafe
    MessageQueue.js:316:6
callFunctionReturnFlushedQueue
    MessageQueue.js:117:17
`

**Comment by Vinu-MysteriousTechVision** [comment]
@danketrotzdem I am sorry for the trouble you are facing. Currently, this sample app is created for the **ios** environment. 
As soon as possible I will update the app for the Android environment also.

**Comment by Vinu-MysteriousTechVision** [comment]
@danketrotzdem I have Updated the code and added working environment in Android
